/*
 * Copyright Bret Ambrose. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

pub static PROPERTY_KEY_PAYLOAD_FORMAT_INDICATOR: u8 = 1;
pub static PROPERTY_KEY_MESSAGE_EXPIRY_INTERVAL: u8 = 2;
pub static PROPERTY_KEY_CONTENT_TYPE: u8 = 3;
pub static PROPERTY_KEY_RESPONSE_TOPIC: u8 = 8;
pub static PROPERTY_KEY_CORRELATION_DATA: u8 = 9;
pub static PROPERTY_KEY_SUBSCRIPTION_IDENTIFIER: u8 = 11;
pub static PROPERTY_KEY_SESSION_EXPIRY_INTERVAL: u8 = 17;
pub static PROPERTY_KEY_ASSIGNED_CLIENT_IDENTIFIER: u8 = 18;
pub static PROPERTY_KEY_SERVER_KEEP_ALIVE: u8 = 19;
pub static PROPERTY_KEY_AUTHENTICATION_METHOD: u8 = 21;
pub static PROPERTY_KEY_AUTHENTICATION_DATA: u8 = 22;
pub static PROPERTY_KEY_REQUEST_PROBLEM_INFORMATION: u8 = 23;
pub static PROPERTY_KEY_WILL_DELAY_INTERVAL: u8 = 24;
pub static PROPERTY_KEY_REQUEST_RESPONSE_INFORMATION: u8 = 25;
pub static PROPERTY_KEY_RESPONSE_INFORMATION: u8 = 26;
pub static PROPERTY_KEY_SERVER_REFERENCE: u8 = 28;
pub static PROPERTY_KEY_REASON_STRING: u8 = 31;
pub static PROPERTY_KEY_RECEIVE_MAXIMUM: u8 = 33;
pub static PROPERTY_KEY_TOPIC_ALIAS_MAXIMUM: u8 = 34;
pub static PROPERTY_KEY_TOPIC_ALIAS: u8 = 35;
pub static PROPERTY_KEY_MAXIMUM_QOS: u8 = 36;
pub static PROPERTY_KEY_RETAIN_AVAILABLE: u8 = 37;
pub static PROPERTY_KEY_USER_PROPERTY: u8 = 38;
pub static PROPERTY_KEY_MAXIMUM_PACKET_SIZE: u8 = 39;
pub static PROPERTY_KEY_WILDCARD_SUBSCRIPTIONS_AVAILABLE: u8 = 40;
pub static PROPERTY_KEY_SUBSCRIPTION_IDENTIFIERS_AVAILABLE: u8 = 41;
pub static PROPERTY_KEY_SHARED_SUBSCRIPTIONS_AVAILABLE: u8 = 42;
