/*
 * Copyright Bret Ambrose. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */

pub const PACKET_TYPE_CONNECT: u8 = 1;
pub const PACKET_TYPE_CONNACK: u8 = 2;
pub const PACKET_TYPE_PUBLISH: u8 = 3;
pub const PACKET_TYPE_PUBACK: u8 = 4;
pub const PACKET_TYPE_PUBREC: u8 = 5;
pub const PACKET_TYPE_PUBREL: u8 = 6;
pub const PACKET_TYPE_PUBCOMP: u8 = 7;
pub const PACKET_TYPE_SUBSCRIBE: u8 = 8;
pub const PACKET_TYPE_SUBACK: u8 = 9;
pub const PACKET_TYPE_UNSUBSCRIBE: u8 = 10;
pub const PACKET_TYPE_UNSUBACK: u8 = 11;
pub const PACKET_TYPE_PINGREQ: u8 = 12;
pub const PACKET_TYPE_PINGRESP: u8 = 13;
pub const PACKET_TYPE_DISCONNECT: u8 = 14;
pub const PACKET_TYPE_AUTH: u8 = 15;

pub const PROPERTY_KEY_PAYLOAD_FORMAT_INDICATOR: u8 = 1;
pub const PROPERTY_KEY_MESSAGE_EXPIRY_INTERVAL: u8 = 2;
pub const PROPERTY_KEY_CONTENT_TYPE: u8 = 3;
pub const PROPERTY_KEY_RESPONSE_TOPIC: u8 = 8;
pub const PROPERTY_KEY_CORRELATION_DATA: u8 = 9;
pub const PROPERTY_KEY_SUBSCRIPTION_IDENTIFIER: u8 = 11;
pub const PROPERTY_KEY_SESSION_EXPIRY_INTERVAL: u8 = 17;
pub const PROPERTY_KEY_ASSIGNED_CLIENT_IDENTIFIER: u8 = 18;
pub const PROPERTY_KEY_SERVER_KEEP_ALIVE: u8 = 19;
pub const PROPERTY_KEY_AUTHENTICATION_METHOD: u8 = 21;
pub const PROPERTY_KEY_AUTHENTICATION_DATA: u8 = 22;
pub const PROPERTY_KEY_REQUEST_PROBLEM_INFORMATION: u8 = 23;
pub const PROPERTY_KEY_WILL_DELAY_INTERVAL: u8 = 24;
pub const PROPERTY_KEY_REQUEST_RESPONSE_INFORMATION: u8 = 25;
pub const PROPERTY_KEY_RESPONSE_INFORMATION: u8 = 26;
pub const PROPERTY_KEY_SERVER_REFERENCE: u8 = 28;
pub const PROPERTY_KEY_REASON_STRING: u8 = 31;
pub const PROPERTY_KEY_RECEIVE_MAXIMUM: u8 = 33;
pub const PROPERTY_KEY_TOPIC_ALIAS_MAXIMUM: u8 = 34;
pub const PROPERTY_KEY_TOPIC_ALIAS: u8 = 35;
pub const PROPERTY_KEY_MAXIMUM_QOS: u8 = 36;
pub const PROPERTY_KEY_RETAIN_AVAILABLE: u8 = 37;
pub const PROPERTY_KEY_USER_PROPERTY: u8 = 38;
pub const PROPERTY_KEY_MAXIMUM_PACKET_SIZE: u8 = 39;
pub const PROPERTY_KEY_WILDCARD_SUBSCRIPTIONS_AVAILABLE: u8 = 40;
pub const PROPERTY_KEY_SUBSCRIPTION_IDENTIFIERS_AVAILABLE: u8 = 41;
pub const PROPERTY_KEY_SHARED_SUBSCRIPTIONS_AVAILABLE: u8 = 42;
